---
# The version of the bootloader.
string bootloader_version

# The version of the firmware.
string firmware_version

# Additional information about the controller in the form of key-value pairs.
# Can be used to provide any additional information about the controller in future versions of the
# firmware without changing the service definition.
raph_interfaces/KeyValue[] extra_information
